version: "3"
services:
  redis-server:
    image: redis
    hostname: gafm-redis
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis-data:/data
    networks:
      net:
        ipv4_address: 172.16.255.10
    container_name: gafm-redis
  gafm-service:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: gafm-srv
    networks:
      net:
        ipv4_address: 172.16.255.11
    ports:
      - "443:443" 
      - "80:443"
      - "8443:443"
    container_name: gafm-srv
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.255.0/24
volumes:
  redis-data:

